language: generic

sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      env:
        - CC=gcc-6
        - CXX=g++-6
      addons:
        apt:
          packages:
            - g++-6
            - lcov
          sources:
            - ubuntu-toolchain-r-test
    - os: linux
      env:
        - CC=clang-4.0
        - CXX=clang++-4.0
      addons:
        apt:
          packages:
            - clang-4.0
            - lcov
          sources:
            - llvm-toolchain-trusty-4.0

script:
  - make test-coverage CXX=$CXX

after_success:
  - bash <(curl -s https://codecov.io/bash)
